# Generated by Django 3.1.3 on 2021-01-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210105_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postpic',
            field=models.ImageField(blank=True, default='bio-image.png', null=True, upload_to=''),
        ),
    ]
