# Generated by Django 3.1.3 on 2021-01-05 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_post_postpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(default=None, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('questions_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': ('Questionnaire',),
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('all_answers', models.ManyToManyField(to='home.Answer')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_category', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='related_product',
            field=models.ManyToManyField(default=None, to='home.Product'),
        ),
    ]
