# Generated by Django 3.1.3 on 2021-01-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210105_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='related_product',
        ),
    ]
