# Generated by Django 3.1.3 on 2021-01-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210105_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='home.Category'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_category',
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ManyToManyField(default=None, to='home.Category'),
        ),
    ]
