# Generated by Django 3.1.3 on 2021-01-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
